In [1]:
from pathlib import Path

import numpy as np
import pandas as pd
import statsmodels.formula.api as smf

DATA = Path(r"C:\Users\tahai\Desktop\EMM-Project\eda_outputs\reciprocity_return.csv")

assert DATA.exists(), f"File not found: {DATA}"

In [2]:
subreddit_sizes = pd.Series(dtype="float64")

for chunk in pd.read_csv(
    DATA,
    usecols=["subreddit"],
    chunksize=200_000,
    keep_default_na=False,
):
    counts = chunk["subreddit"].value_counts()

    subreddit_sizes = subreddit_sizes.add(
        counts,
        fill_value=0
    )

    selected_subreddits = subreddit_sizes.index
    print("Subreddits:", len(selected_subreddits))
    display(subreddit_sizes.loc[selected_subreddits])

Subreddits: 17

subreddit
Awesomenauts             3305.0
MLPCCG                   1246.0
MLPLounge               10622.0
MLS                       257.0
MensRights                998.0
Miniswap                 1572.0
Minneapolis              3976.0
aviation                14711.0
awesome                  2419.0
aww                     32109.0
gifs                    53248.0
minimalism               5724.0
minnesota                4851.0
minnesotavikings        10712.0
misc                     2468.0
misleadingthumbnails     4678.0
soccer                  47104.0
dtype: float64

Subreddits: 26

subreddit
Awesomenauts              3305.0
MLPCCG                    1246.0
MLPLounge                10622.0
MLS                      28403.0
MMA                      21006.0
MensRights                 998.0
Miniswap                  1572.0
Minneapolis               3976.0
SoccerBetting             2307.0
WeAreTheMusicMakers       3333.0
aviation                 14711.0
awesome                   2419.0
aww                      80557.0
gifs                    103582.0
granturismo                866.0
minimalism                5724.0
minnesota                 4851.0
minnesotavikings         10712.0
misc                      2468.0
misleadingthumbnails      4678.0
soccer                   81897.0
socialanxiety             1833.0
weather                   2616.0
webcomics                 3164.0
webdev                    2560.0
worldnews                  594.0
dtype: float64

Subreddits: 31

subreddit
Awesomenauts              3305.0
MLPCCG                    1246.0
MLPLounge                10622.0
MLS                      28403.0
MMA                      31718.0
MensRights                8014.0
Miniswap                  1572.0
Minneapolis               3976.0
SoccerBetting             2307.0
WeAreTheMusicMakers       3333.0
apple                    24576.0
aviation                 14711.0
awesome                   2419.0
aww                      99895.0
funny                    28672.0
gifs                    106132.0
granturismo               2279.0
graphic_design            9555.0
gratefuldead               448.0
leagueoflegends          22528.0
minimalism                5724.0
minnesota                 4851.0
minnesotavikings         10712.0
misc                      2468.0
misleadingthumbnails      4678.0
soccer                   97809.0
socialanxiety             1833.0
weather                   2616.0
webcomics                 3164.0
webdev                    2560.0
worldnews                57874.0
dtype: float64

Subreddits: 45

subreddit
ANormalDayInRussia        6631.0
AnimeFigures              1616.0
AnimeSketch               1577.0
Animesuggest             13388.0
AnnArbor                  1845.0
Awesomenauts              3305.0
JusticePorn              25944.0
MLPCCG                    1246.0
MLPLounge                10622.0
MLS                      28403.0
MMA                      31718.0
MensRights                8014.0
Miniswap                  1572.0
Minneapolis               3976.0
Redskins                   260.0
ReefTank                  3410.0
Reformed                  1843.0
SoccerBetting             2307.0
WeAreTheMusicMakers       3333.0
animegifs                 1725.0
anonymous                 1166.0
answers                   6490.0
apple                    40178.0
aviation                 14711.0
awesome                   2419.0
aww                      99895.0
funny                    75008.0
gifs                    106132.0
granturismo               2279.0
graphic_design            9555.0
gratefuldead               448.0
leagueoflegends          53928.0
minimalism                5724.0
minnesota                 4851.0
minnesotavikings         10712.0
misc                      2468.0
misleadingthumbnails      4678.0
redsox                    5844.0
relationships            20145.0
soccer                   97809.0
socialanxiety             1833.0
weather                   2616.0
webcomics                 3164.0
webdev                    2560.0
worldnews                72652.0
dtype: float64

Subreddits: 54

subreddit
ANormalDayInRussia        6631.0
AdviceAnimals             8192.0
AnimeFigures              1616.0
AnimeSketch               1577.0
Animesuggest             13388.0
AnnArbor                  1845.0
AntiJokes                 3012.0
Anticonsumption           2394.0
Anxiety                  10409.0
AnythingGoesNews          2073.0
AppHookup                 3894.0
AppalachianTrail          1734.0
Awesomenauts              3305.0
JusticePorn              25944.0
MLPCCG                    1246.0
MLPLounge                10622.0
MLS                      28403.0
MMA                      31718.0
MensRights                8014.0
Miniswap                  1572.0
Minneapolis               3976.0
Redskins                   260.0
ReefTank                  3410.0
Reformed                  1843.0
SoccerBetting             2307.0
WeAreTheMusicMakers       3333.0
animegifs                 1725.0
anonymous                 1166.0
answers                   8209.0
aoe2                      2607.0
apple                    53296.0
aviation                 14711.0
awesome                   2419.0
aww                      99895.0
fantasyfootball           2048.0
funny                   122880.0
gifs                    106132.0
granturismo               2279.0
graphic_design            9555.0
gratefuldead               448.0
leagueoflegends          96936.0
minimalism                5724.0
minnesota                 4851.0
minnesotavikings         10712.0
misc                      2468.0
misleadingthumbnails      4678.0
redsox                    5844.0
relationships            78065.0
soccer                   97809.0
socialanxiety             1833.0
weather                   2616.0
webcomics                 3164.0
webdev                    2560.0
worldnews                72652.0
dtype: float64

Subreddits: 60

subreddit
ANormalDayInRussia        6631.0
AdviceAnimals            57344.0
AnimeFigures              1616.0
AnimeSketch               1577.0
Animesuggest             13388.0
AnnArbor                  1845.0
AntiJokes                 3012.0
Anticonsumption           2394.0
Anxiety                  10409.0
AnythingGoesNews          2073.0
AppHookup                 3894.0
AppalachianTrail          1734.0
Awesomenauts              3305.0
JusticePorn              25944.0
LearnJapanese              439.0
MLPCCG                    1246.0
MLPLounge                10622.0
MLS                      28403.0
MMA                      31718.0
MensRights                8014.0
Miniswap                  1572.0
Minneapolis               3976.0
Redskins                   260.0
ReefTank                  3410.0
Reformed                  1843.0
SoccerBetting             2307.0
WeAreTheMusicMakers       3333.0
animegifs                 1725.0
anonymous                 1166.0
answers                   8209.0
aoe2                      2607.0
apple                    53296.0
aviation                 14711.0
awesome                   2419.0
aww                      99895.0
fantasyfootball          47104.0
funny                   122880.0
gifs                    106132.0
granturismo               2279.0
graphic_design            9555.0
gratefuldead               448.0
leagueoflegends          96936.0
learnmath                 5619.0
learnprogramming         28920.0
learnpython               2749.0
minimalism                5724.0
minnesota                 4851.0
minnesotavikings         10712.0
misc                      2468.0
misleadingthumbnails      4678.0
polandball               11425.0
redsox                    5844.0
relationships            96696.0
soccer                   97809.0
socialanxiety             1833.0
videos                   38009.0
weather                   2616.0
webcomics                 3164.0
webdev                    2560.0
worldnews                72652.0
dtype: float64

Subreddits: 69

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         112640.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
videos                 50113.0
weather                 2616.0
webcomics               3164.0
webdev                  2560.0
worldnews              72652.0
Length: 69, dtype: float64

Subreddits: 85

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         122880.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
webcomics               3164.0
webdev                  2560.0
worldnews              72652.0
xboxone                28069.0
xmen                    2301.0
Length: 85, dtype: float64

Subreddits: 99

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         122880.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 99, dtype: float64

Subreddits: 119

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         122880.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 119, dtype: float64

Subreddits: 132

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         122880.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 132, dtype: float64

Subreddits: 145

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         122880.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 145, dtype: float64

Subreddits: 164

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         122880.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 164, dtype: float64

Subreddits: 181

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         122880.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 181, dtype: float64

Subreddits: 204

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         122880.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 204, dtype: float64

Subreddits: 218

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         122880.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 218, dtype: float64

Subreddits: 230

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         122880.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 230, dtype: float64

Subreddits: 243

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         122880.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 243, dtype: float64

Subreddits: 254

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         122880.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 254, dtype: float64

Subreddits: 266

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         122880.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 266, dtype: float64

Subreddits: 276

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         122880.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 276, dtype: float64

Subreddits: 284

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         122880.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 284, dtype: float64

Subreddits: 289

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         122880.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 289, dtype: float64

Subreddits: 289

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         122880.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 289, dtype: float64

Subreddits: 301

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         161792.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 301, dtype: float64

Subreddits: 311

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         206976.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 311, dtype: float64

Subreddits: 318

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         245760.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 318, dtype: float64

Subreddits: 342

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         245760.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 342, dtype: float64

Subreddits: 369

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         245760.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 369, dtype: float64

Subreddits: 385

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         245760.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 385, dtype: float64

Subreddits: 401

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         245760.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 401, dtype: float64

Subreddits: 409

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         245760.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 409, dtype: float64

Subreddits: 429

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         245760.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 429, dtype: float64

Subreddits: 436

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         245760.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 436, dtype: float64

Subreddits: 441

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         245760.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 441, dtype: float64

Subreddits: 449

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         245760.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 449, dtype: float64

Subreddits: 462

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         245760.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 462, dtype: float64

Subreddits: 476

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         245760.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 476, dtype: float64

Subreddits: 480

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         286399.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 480, dtype: float64

Subreddits: 496

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         308017.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 496, dtype: float64

Subreddits: 511

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         355121.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 511, dtype: float64

Subreddits: 528

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         366803.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 528, dtype: float64

Subreddits: 538

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         366803.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 538, dtype: float64

Subreddits: 553

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         366803.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 553, dtype: float64

Subreddits: 553

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         366803.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 553, dtype: float64

Subreddits: 557

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         366803.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 557, dtype: float64

Subreddits: 565

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         413662.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 565, dtype: float64

Subreddits: 565

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         458718.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 565, dtype: float64

Subreddits: 575

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         489683.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 575, dtype: float64

Subreddits: 583

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         489683.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 583, dtype: float64

Subreddits: 590

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         489683.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 590, dtype: float64

Subreddits: 599

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         489683.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 599, dtype: float64

Subreddits: 604

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         489683.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 604, dtype: float64

Subreddits: 609

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         489683.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 609, dtype: float64

Subreddits: 613

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         489683.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 613, dtype: float64

Subreddits: 613

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         489683.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 613, dtype: float64

Subreddits: 621

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         489683.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 621, dtype: float64

Subreddits: 631

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         489683.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 631, dtype: float64

Subreddits: 633

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         495827.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 633, dtype: float64

Subreddits: 645

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         559315.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 645, dtype: float64

Subreddits: 658

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         612563.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 658, dtype: float64

Subreddits: 667

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         612563.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 667, dtype: float64

Subreddits: 680

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         612563.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 680, dtype: float64

Subreddits: 693

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         612563.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 693, dtype: float64

Subreddits: 703

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         612563.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 703, dtype: float64

Subreddits: 718

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         612563.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 718, dtype: float64

Subreddits: 726

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         612563.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 726, dtype: float64

Subreddits: 735

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         612563.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 735, dtype: float64

Subreddits: 745

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         612563.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 745, dtype: float64

Subreddits: 750

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         612563.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 750, dtype: float64

Subreddits: 759

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         612563.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 759, dtype: float64

Subreddits: 762

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         612563.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 762, dtype: float64

Subreddits: 769

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         612563.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 769, dtype: float64

Subreddits: 777

subreddit
ANormalDayInRussia      6631.0
AdviceAnimals         612563.0
AnimeFigures            1616.0
AnimeSketch             1577.0
Animesuggest           13388.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 777, dtype: float64

Subreddits: 795

subreddit
ACMilan                 1629.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         612563.0
AnimeFigures            1616.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 795, dtype: float64

Subreddits: 810

subreddit
ACMilan                 1629.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         612563.0
AnimeFigures            1616.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 810, dtype: float64

Subreddits: 819

subreddit
ACMilan                 1629.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         612563.0
AnimeFigures            1616.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 819, dtype: float64

Subreddits: 822

subreddit
ACMilan                 1629.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         612563.0
AnimeFigures            1616.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 822, dtype: float64

Subreddits: 837

subreddit
ACMilan                 1629.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         612563.0
AnimeFigures            1616.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 837, dtype: float64

Subreddits: 854

subreddit
ACMilan                 1629.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         612563.0
AnimeFigures            2681.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 854, dtype: float64

Subreddits: 876

subreddit
ACMilan                 1629.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         612563.0
AnimeFigures            2681.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 876, dtype: float64

Subreddits: 901

subreddit
ACMilan                 1629.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         612563.0
AnimeFigures            2681.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 901, dtype: float64

Subreddits: 914

subreddit
ACMilan                 1629.0
AFL                     7841.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         612563.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 914, dtype: float64

Subreddits: 929

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         612563.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 929, dtype: float64

Subreddits: 931

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         612563.0
                        ...
xmen                    3669.0
xxfitness              15628.0
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
Length: 931, dtype: float64

Subreddits: 942

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         659875.0
                        ...
xxketo                  6877.0
yiff                    2644.0
yoga                     964.0
yugioh                   812.0
zelda                   3993.0
Length: 942, dtype: float64

Subreddits: 952

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         708532.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 952, dtype: float64

Subreddits: 966

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         708532.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 966, dtype: float64

Subreddits: 980

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         708532.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 980, dtype: float64

Subreddits: 984

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         708532.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 984, dtype: float64

Subreddits: 991

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         708532.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 991, dtype: float64

Subreddits: 994

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         708532.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 994, dtype: float64

Subreddits: 1016

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         708532.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1016, dtype: float64

Subreddits: 1027

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         708532.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1027, dtype: float64

Subreddits: 1040

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         708532.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1040, dtype: float64

Subreddits: 1048

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         708532.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1048, dtype: float64

Subreddits: 1057

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         708532.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1057, dtype: float64

Subreddits: 1071

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         708532.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1071, dtype: float64

Subreddits: 1080

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         708532.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1080, dtype: float64

Subreddits: 1098

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         708532.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1098, dtype: float64

Subreddits: 1112

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         708532.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1112, dtype: float64

Subreddits: 1135

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         708532.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1135, dtype: float64

Subreddits: 1151

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         726167.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1151, dtype: float64

Subreddits: 1158

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         804084.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1158, dtype: float64

Subreddits: 1169

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         831412.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1169, dtype: float64

Subreddits: 1178

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         831412.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1178, dtype: float64

Subreddits: 1196

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         831412.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1196, dtype: float64

Subreddits: 1206

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         831412.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1206, dtype: float64

Subreddits: 1220

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         831412.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1220, dtype: float64

Subreddits: 1226

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         831412.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1226, dtype: float64

Subreddits: 1234

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         831412.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1234, dtype: float64

Subreddits: 1241

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         831412.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1241, dtype: float64

Subreddits: 1251

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         831412.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1251, dtype: float64

Subreddits: 1259

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         831412.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1259, dtype: float64

Subreddits: 1268

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         831412.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1268, dtype: float64

Subreddits: 1276

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         831412.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1276, dtype: float64

Subreddits: 1287

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         831412.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1287, dtype: float64

Subreddits: 1302

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         831412.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1302, dtype: float64

Subreddits: 1310

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         831412.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1310, dtype: float64

Subreddits: 1316

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         843700.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1316, dtype: float64

Subreddits: 1322

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         895767.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1322, dtype: float64

Subreddits: 1338

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         944965.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1338, dtype: float64

Subreddits: 1351

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         944965.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1351, dtype: float64

Subreddits: 1373

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         944965.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1373, dtype: float64

Subreddits: 1387

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         953403.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1387, dtype: float64

Subreddits: 1392

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         983671.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1392, dtype: float64

Subreddits: 1397

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         983671.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1397, dtype: float64

Subreddits: 1412

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         983671.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1412, dtype: float64

Subreddits: 1420

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         983671.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1420, dtype: float64

Subreddits: 1423

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         983671.0
                        ...
yoga                     964.0
yugioh                   812.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1423, dtype: float64

Subreddits: 1433

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         983671.0
                        ...
youtubehaiku            7500.0
yugioh                 16250.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1433, dtype: float64

Subreddits: 1441

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         983671.0
                        ...
youtubehaiku           20990.0
yugioh                 16250.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1441, dtype: float64

Subreddits: 1446

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         983671.0
                        ...
youtubehaiku           20990.0
yugioh                 16250.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1446, dtype: float64

Subreddits: 1459

subreddit
ACMilan                 1629.0
AFL                     9848.0
ANormalDayInRussia      6631.0
Accounting              5723.0
AdviceAnimals         983671.0
                        ...
youtubehaiku           20990.0
yugioh                 16250.0
zelda                  15425.0
zen                     2812.0
zombies                 3727.0
Length: 1459, dtype: float64

Subreddits: 1470

subreddit
4chan                 47104.0
ACMilan                1629.0
AFL                    9848.0
ANormalDayInRussia     6631.0
Accounting             5723.0
                       ...
youtubehaiku          20990.0
yugioh                16250.0
zelda                 15425.0
zen                    2812.0
zombies                3727.0
Length: 1470, dtype: float64

Subreddits: 1486

subreddit
4chan           73901.0
4x4              4986.0
90daysgoal       1166.0
911truth         1300.0
ABDL             2392.0
                 ...
youtubehaiku    20990.0
yugioh          16250.0
zelda           15425.0
zen              2812.0
zombies          3727.0
Length: 1486, dtype: float64

Subreddits: 1497

subreddit
4chan           73901.0
4x4              4986.0
90daysgoal       1166.0
911truth         1300.0
ABDL             2392.0
                 ...
youtubehaiku    20990.0
yugioh          16250.0
zelda           15425.0
zen              2812.0
zombies          3727.0
Length: 1497, dtype: float64

Subreddits: 1497

subreddit
4chan           73901.0
4x4              4986.0
90daysgoal       1166.0
911truth         1300.0
ABDL             2392.0
                 ...
youtubehaiku    20990.0
yugioh          16250.0
zelda           15425.0
zen              2812.0
zombies          3727.0
Length: 1497, dtype: float64

Subreddits: 1514

subreddit
4chan           73901.0
4x4              4986.0
90daysgoal       1166.0
911truth         1300.0
ABDL             2392.0
                 ...
youtubehaiku    20990.0
yugioh          16250.0
zelda           15425.0
zen              2812.0
zombies          3727.0
Length: 1514, dtype: float64

Subreddits: 1526

subreddit
4chan           73901.0
4x4              4986.0
90daysgoal       1166.0
911truth         1300.0
ABDL             2392.0
                 ...
youtubehaiku    20990.0
yugioh          16250.0
zelda           15425.0
zen              2812.0
zombies          3727.0
Length: 1526, dtype: float64

Subreddits: 1538

subreddit
4chan           73901.0
4x4              4986.0
90daysgoal       1166.0
911truth         1300.0
ABDL             2392.0
                 ...
youtubehaiku    20990.0
yugioh          16250.0
zelda           15425.0
zen              2812.0
zombies          3727.0
Length: 1538, dtype: float64

Subreddits: 1554

subreddit
4chan           73901.0
4x4              4986.0
90daysgoal       1166.0
911truth         1300.0
ABDL             2392.0
                 ...
youtubehaiku    20990.0
yugioh          16250.0
zelda           15425.0
zen              2812.0
zombies          3727.0
Length: 1554, dtype: float64

Subreddits: 1578

subreddit
4chan           73901.0
4x4              4986.0
90daysgoal       1166.0
911truth         1300.0
ABDL             2392.0
                 ...
youtubehaiku    20990.0
yugioh          16250.0
zelda           15425.0
zen              2812.0
zombies          3727.0
Length: 1578, dtype: float64

Subreddits: 1597

subreddit
4chan           73901.0
4x4              4986.0
90daysgoal       1166.0
911truth         1300.0
ABDL             2392.0
                 ...
youtubehaiku    20990.0
yugioh          16250.0
zelda           15425.0
zen              2812.0
zombies          3727.0
Length: 1597, dtype: float64

Subreddits: 1612

subreddit
4chan           73901.0
4x4              4986.0
90daysgoal       1166.0
911truth         1300.0
ABDL             2392.0
                 ...
youtubehaiku    20990.0
yugioh          16250.0
zelda           15425.0
zen              2812.0
zombies          3727.0
Length: 1612, dtype: float64

Subreddits: 1626

subreddit
4chan           73901.0
4x4              4986.0
90daysgoal       1166.0
911truth         1300.0
ABDL             2392.0
                 ...
youtubehaiku    20990.0
yugioh          16250.0
zelda           15425.0
zen              2812.0
zombies          3727.0
Length: 1626, dtype: float64

Subreddits: 1650

subreddit
4chan           73901.0
4x4              4986.0
90daysgoal       1166.0
911truth         1300.0
ABDL             2392.0
                 ...
youtubehaiku    20990.0
yugioh          16250.0
zelda           15425.0
zen              2812.0
zombies          3727.0
Length: 1650, dtype: float64

Subreddits: 1666

subreddit
4chan           73901.0
4x4              4986.0
90daysgoal       1166.0
911truth         1300.0
ABDL             2392.0
                 ...
youtubehaiku    20990.0
yugioh          16250.0
zelda           15425.0
zen              2812.0
zombies          3727.0
Length: 1666, dtype: float64

Subreddits: 1685

subreddit
4chan           73901.0
4x4              4986.0
90daysgoal       1166.0
911truth         1300.0
ABDL             2392.0
                 ...
youtubehaiku    20990.0
yugioh          16250.0
zelda           15425.0
zen              2812.0
zombies          3727.0
Length: 1685, dtype: float64

Subreddits: 1699

subreddit
4chan           73901.0
4x4              4986.0
90daysgoal       1166.0
911truth         1300.0
ABDL             2392.0
                 ...
youtubehaiku    20990.0
yugioh          16250.0
zelda           15425.0
zen              2812.0
zombies          3727.0
Length: 1699, dtype: float64

Subreddits: 1714

subreddit
4chan           73901.0
4x4              4986.0
90daysgoal       1166.0
911truth         1300.0
ABDL             2392.0
                 ...
youtubehaiku    20990.0
yugioh          16250.0
zelda           15425.0
zen              2812.0
zombies          3727.0
Length: 1714, dtype: float64

Subreddits: 1726

subreddit
4chan           73901.0
4x4              4986.0
90daysgoal       1166.0
911truth         1300.0
ABDL             2392.0
                 ...
youtubehaiku    20990.0
yugioh          16250.0
zelda           15425.0
zen              2812.0
zombies          3727.0
Length: 1726, dtype: float64

Subreddits: 1734

subreddit
4chan           73901.0
4x4              4986.0
90daysgoal       1166.0
911truth         1300.0
ABDL             2392.0
                 ...
youtubehaiku    20990.0
yugioh          16250.0
zelda           15425.0
zen              2812.0
zombies          3727.0
Length: 1734, dtype: float64

Subreddits: 1747

subreddit
4chan           73901.0
4x4              4986.0
90daysgoal       1166.0
911truth         1300.0
ABDL             2392.0
                 ...
youtubehaiku    20990.0
yugioh          16250.0
zelda           15425.0
zen              2812.0
zombies          3727.0
Length: 1747, dtype: float64

Subreddits: 1765

subreddit
4chan           73901.0
4x4              4986.0
90daysgoal       1166.0
911truth         1300.0
ABDL             2392.0
                 ...
youtubehaiku    20990.0
yugioh          16250.0
zelda           15425.0
zen              2812.0
zombies          3727.0
Length: 1765, dtype: float64

Subreddits: 1783

subreddit
4chan           73901.0
4x4              4986.0
90daysgoal       1166.0
911truth         1300.0
ABDL             2392.0
                 ...
youtubehaiku    20990.0
yugioh          16250.0
zelda           15425.0
zen              2812.0
zombies          3727.0
Length: 1783, dtype: float64

Subreddits: 1792

subreddit
3DS             30183.0
3dsFCswap        2449.0
49ers            4465.0
4chan           73901.0
4x4              4986.0
                 ...
youtubehaiku    20990.0
yugioh          16250.0
zelda           15425.0
zen              2812.0
zombies          3727.0
Length: 1792, dtype: float64

Subreddits: 1804

subreddit
2007scape       20166.0
3DS             30183.0
3dsFCswap        2449.0
49ers           12093.0
4chan           93658.0
                 ...
youtubehaiku    20990.0
yugioh          16250.0
zelda           15425.0
zen              2812.0
zombies          3727.0
Length: 1804, dtype: float64

Subreddits: 1816

subreddit
2007scape        24694.0
240sx             1960.0
24hoursupport     2226.0
3DS              35874.0
3Dprinting        9313.0
                  ...
youtubehaiku     20990.0
yugioh           16250.0
zelda            15425.0
zen               2812.0
zombies           3727.0
Length: 1816, dtype: float64

Subreddits: 1831

subreddit
2007scape        24694.0
240sx             1960.0
24hoursupport     2226.0
3DS              35874.0
3Dprinting        9313.0
                  ...
youtubehaiku     20990.0
yugioh           16250.0
zelda            15425.0
zen               2812.0
zombies           3727.0
Length: 1831, dtype: float64

Subreddits: 1837

subreddit
2007scape        24694.0
240sx             1960.0
24hoursupport     2226.0
3DS              35874.0
3Dprinting        9313.0
                  ...
youtubehaiku     20990.0
yugioh           16250.0
zelda            15425.0
zen               2812.0
zombies           3727.0
Length: 1837, dtype: float64

Subreddits: 1846

subreddit
2007scape        24694.0
240sx             1960.0
24hoursupport     2226.0
3DS              35874.0
3Dprinting        9313.0
                  ...
youtubehaiku     20990.0
yugioh           16250.0
zelda            15425.0
zen               2812.0
zombies           3727.0
Length: 1846, dtype: float64

Subreddits: 1857

subreddit
2007scape        24694.0
240sx             1960.0
24hoursupport     2226.0
3DS              35874.0
3Dprinting        9313.0
                  ...
youtubehaiku     20990.0
yugioh           16250.0
zelda            15425.0
zen               2812.0
zombies           3727.0
Length: 1857, dtype: float64

Subreddits: 1872

subreddit
2007scape        24694.0
240sx             1960.0
24hoursupport     2226.0
3DS              35874.0
3Dprinting        9313.0
                  ...
youtubehaiku     20990.0
yugioh           16250.0
zelda            15425.0
zen               2812.0
zombies           3727.0
Length: 1872, dtype: float64

Subreddits: 1877

subreddit
2007scape        24694.0
240sx             1960.0
24hoursupport     2226.0
3DS              35874.0
3Dprinting        9313.0
                  ...
youtubehaiku     20990.0
yugioh           16250.0
zelda            15425.0
zen               2812.0
zombies           3727.0
Length: 1877, dtype: float64

Subreddits: 1889

subreddit
2007scape        24694.0
240sx             1960.0
24hoursupport     2226.0
3DS              35874.0
3Dprinting        9313.0
                  ...
youtubehaiku     20990.0
yugioh           16250.0
zelda            15425.0
zen               2812.0
zombies           3727.0
Length: 1889, dtype: float64

Subreddits: 1903

subreddit
2007scape        24694.0
240sx             1960.0
24hoursupport     2226.0
3DS              35874.0
3Dprinting        9313.0
                  ...
youtubehaiku     20990.0
yugioh           16250.0
zelda            15425.0
zen               2812.0
zombies           3727.0
Length: 1903, dtype: float64

Subreddits: 1912

subreddit
2007scape        24694.0
240sx             1960.0
24hoursupport     2226.0
3DS              35874.0
3Dprinting        9313.0
                  ...
youtubehaiku     20990.0
yugioh           16250.0
zelda            15425.0
zen               2812.0
zombies           3727.0
Length: 1912, dtype: float64

Subreddits: 1920

subreddit
2007scape        24694.0
240sx             1960.0
24hoursupport     2226.0
3DS              35874.0
3Dprinting        9313.0
                  ...
youtubehaiku     20990.0
yugioh           16250.0
zelda            15425.0
zen               2812.0
zombies           3727.0
Length: 1920, dtype: float64

Subreddits: 1934

subreddit
2007scape        24694.0
240sx             1960.0
24hoursupport     2226.0
3DS              35874.0
3Dprinting        9313.0
                  ...
youtubehaiku     20990.0
yugioh           16250.0
zelda            15425.0
zen               2812.0
zombies           3727.0
Length: 1934, dtype: float64

Subreddits: 1948

subreddit
2007scape        24694.0
240sx             1960.0
24hoursupport     2226.0
3DS              35874.0
3Dprinting        9313.0
                  ...
youtubehaiku     20990.0
yugioh           16250.0
zelda            15425.0
zen               2812.0
zombies           3727.0
Length: 1948, dtype: float64

Subreddits: 1962

subreddit
2007scape        24694.0
240sx             1960.0
24hoursupport     2226.0
3DS              35874.0
3Dprinting        9313.0
                  ...
youtubehaiku     20990.0
yugioh           16250.0
zelda            15425.0
zen               2812.0
zombies           3727.0
Length: 1962, dtype: float64

Subreddits: 1969

subreddit
2007scape        24694.0
240sx             1960.0
24hoursupport     2226.0
3DS              35874.0
3Dprinting        9313.0
                  ...
youtubehaiku     20990.0
yugioh           16250.0
zelda            15425.0
zen               2812.0
zombies           3727.0
Length: 1969, dtype: float64

Subreddits: 1978

subreddit
2007scape        24694.0
240sx             1960.0
24hoursupport     2226.0
3DS              35874.0
3Dprinting        9313.0
                  ...
youtubehaiku     20990.0
yugioh           16250.0
zelda            15425.0
zen               2812.0
zombies           3727.0
Length: 1978, dtype: float64

Subreddits: 1990

subreddit
2007scape        24694.0
240sx             1960.0
24hoursupport     2226.0
3DS              35874.0
3Dprinting        9313.0
                  ...
youtubehaiku     20990.0
yugioh           16250.0
zelda            15425.0
zen               2812.0
zombies           3727.0
Length: 1990, dtype: float64

Subreddits: 2000

subreddit
2007scape        24694.0
240sx             1960.0
24hoursupport     2226.0
3DS              35874.0
3Dprinting        9313.0
                  ...
youtubehaiku     20990.0
yugioh           16250.0
zelda            15425.0
zen               2812.0
zombies           3727.0
Length: 2000, dtype: float64

Subreddits: 2008

subreddit
2007scape        24694.0
240sx             1960.0
24hoursupport     2226.0
3DS              35874.0
3Dprinting        9313.0
                  ...
youtubehaiku     20990.0
yugioh           16250.0
zelda            15425.0
zen               2812.0
zombies           3727.0
Length: 2008, dtype: float64

Subreddits: 2020

subreddit
2007scape        24694.0
240sx             1960.0
24hoursupport     2226.0
3DS              35874.0
3Dprinting        9313.0
                  ...
youtubehaiku     20990.0
yugioh           16250.0
zelda            15425.0
zen               2812.0
zombies           3727.0
Length: 2020, dtype: float64

Subreddits: 2031

subreddit
2007scape        24694.0
240sx             1960.0
24hoursupport     2226.0
3DS              35874.0
3Dprinting        9313.0
                  ...
youtubehaiku     20990.0
yugioh           16250.0
zelda            15425.0
zen               2812.0
zombies           3727.0
Length: 2031, dtype: float64

Subreddits: 2043

subreddit
2007scape        24694.0
240sx             1960.0
24hoursupport     2226.0
3DS              35874.0
3Dprinting        9313.0
                  ...
youtubehaiku     20990.0
yugioh           16250.0
zelda            15425.0
zen               2812.0
zombies           3727.0
Length: 2043, dtype: float64

Subreddits: 2046

subreddit
2007scape        24694.0
240sx             1960.0
24hoursupport     2226.0
3DS              35874.0
3Dprinting        9313.0
                  ...
youtubehaiku     20990.0
yugioh           16250.0
zelda            15425.0
zen               2812.0
zombies           3727.0
Length: 2046, dtype: float64

In [3]:
print("Output test")
print(subreddit_sizes.nlargest(20).to_string())

Output test
subreddit
funny                1382467.0
pics                 1152645.0
AdviceAnimals         996617.0
videos                845372.0
todayilearned         801297.0
WTF                   768546.0
gaming                688165.0
worldnews             612859.0
leagueoflegends       586630.0
IAmA                  455735.0
news                  420886.0
movies                417290.0
gifs                  387487.0
technology            319097.0
explainlikeimfive     307611.0
aww                   289729.0
nfl                   243292.0
soccer                237899.0
DotA2                 232726.0
politics              230155.0

In [4]:
columns = [
    "user",
    "subreddit",
    "month",
    "replies_sent",
    "replies_received",
    "reciprocal_partners",
    "returned_next_month",
]

target_rows = 50_000

sample_fraction = 1.0

parts = []

for chunk in pd.read_csv(
    DATA,
    usecols=columns,
    dtype={"user": str, "subreddit": str},
    chunksize=200_000,
    keep_default_na=False,
):
    chunk = chunk[
        chunk["subreddit"].isin(selected_subreddits)
    ].copy()

    user_hash = pd.util.hash_pandas_object(
        chunk["user"],
        index=False,
    )

    keep_user = (
        user_hash % 1_000_003
    ) < sample_fraction * 1_000_003

    parts.append(chunk.loc[keep_user])

df = pd.concat(parts, ignore_index=True)
del parts

df["user"] = df["user"].astype("category")
df["subreddit"] = df["subreddit"].astype("category")

print("Rows:", len(df))
print("Users:", df["user"].nunique())
print("Subreddits:", df["subreddit"].nunique())

display(df.head())

Rows: 36031393
Users: 3354982
Subreddits: 2046

,subreddit,month,user,replies_sent,replies_received,reciprocal_partners,returned_next_month
0,gifs,2,Cyykratahk,1,1,0,0
1,gifs,2,gramcraka92,1,4,0,0
2,gifs,2,H_E_Pennypacker,1,1,1,0
3,gifs,2,Interestinglyuseless,1,5,0,1
4,gifs,2,dryguy5,3,0,0,1

In [5]:
df["recip_binary"] = (
    df["reciprocal_partners"] > 0
).astype(int)

df["log_sent"] = np.log1p(df["replies_sent"])
df["log_received"] = np.log1p(df["replies_received"])

assert not df.empty
assert not df.isna().any().any()

assert not df.duplicated(
    ["user", "subreddit", "month"]
).any(), "Duplicate user-subreddit-month rows found."

assert set(df["returned_next_month"].unique()) == {0, 1}
assert set(df["recip_binary"].unique()) == {0, 1}

assert (
    df[["replies_sent", "replies_received", "reciprocal_partners"]]
    >= 0
).all().all()

assert np.isfinite(
    df[["log_sent", "log_received"]].to_numpy()
).all()

for column in ["subreddit", "month"]:
    variation = df.groupby(column)["returned_next_month"].nunique()
    assert variation.eq(2).all(), (
        f"Some {column} groups contain only one return outcome."
    )

display(
    pd.crosstab(
        df["recip_binary"],
        df["returned_next_month"],
    )
)

C:\Users\tahai\AppData\Local\Temp\ipykernel_52344\2063673150.py:28: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  variation = df.groupby(column)["returned_next_month"].nunique()

returned_next_month         0        1
recip_binary
0                    12447185  4758717
1                    10473095  8352396

In [6]:
print("Kernel is responding", flush=True)
print("Data shape:", df.shape, flush=True)

Kernel is responding
Data shape: (36031393, 10)

In [7]:
import pyfixest as pf

model = pf.feglm(
    "returned_next_month ~ recip_binary + log_sent + log_received"
    " | month + subreddit",
    data=df,
    family="logit",
    vcov={"CRV1": "user"},
    copy_data=False,
    fixef_rm="none",
    iwls_maxiter=100,
)

assert model.convergence, "Model did not converge."

display(model.tidy())

              Estimate  Std. Error     t value  Pr(>|t|)      2.5%     97.5%
Coefficient
recip_binary -0.241267    0.001146 -210.468681       0.0 -0.243514 -0.239020
log_sent      1.252967    0.001615  775.704071       0.0  1.249801  1.256133
log_received  0.299754    0.001105  271.361373       0.0  0.297589  0.301919

In [8]:
from scipy.special import expit

eta = model.predict(type="link")

assert len(eta) == len(df), "Some observations were excluded."
assert np.isfinite(eta).all(), "Some fitted values are missing or invalid."

beta = model.coef().loc["recip_binary"]

score_without_reciprocity = (
    eta - beta * df["recip_binary"].to_numpy()
)

average_difference = (
    expit(score_without_reciprocity + beta)
    - expit(score_without_reciprocity)
).mean()

print(
    "Adjusted average difference:",
    f"{100 * average_difference:.2f} percentage points",
)

Adjusted average difference: -4.44 percentage points

In [22]:
display(model.tidy().loc["recip_binary"])

Estimate       -0.241267
Std. Error      0.001146
t value      -210.468681
Pr(>|t|)        0.000000
2.5%           -0.243514
97.5%          -0.239020
Name: recip_binary, dtype: float64